# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Havlu < Formula
  desc "Havlu lets you focus on the frontend by making it effortless to have a custom API."
  homepage ""
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fdemir/havlu/releases/download/v0.1.9/havlu_Darwin_arm64.tar.gz"
      sha256 "6a93b727460b50dc7e48ba07ec2bc3840afde826477d48a049a1e3004057fd93"

      def install
        bin.install "havlu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fdemir/havlu/releases/download/v0.1.9/havlu_Darwin_x86_64.tar.gz"
      sha256 "09eca8527f79866eb6930e8d589e8f693c12a189c06aaa17a93ee28765150ec9"

      def install
        bin.install "havlu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fdemir/havlu/releases/download/v0.1.9/havlu_Linux_arm64.tar.gz"
      sha256 "edc24c48317f49ea601e1313ad88aa803935e4a1ee5c7070c4730a69a232ed18"

      def install
        bin.install "havlu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fdemir/havlu/releases/download/v0.1.9/havlu_Linux_x86_64.tar.gz"
      sha256 "11a88a678ed99a0645b17777bc6b9db861bf305e42ec1640202d251d64d25576"

      def install
        bin.install "havlu"
      end
    end
  end
end
