# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Havlu < Formula
  desc "Havlu lets you focus on the frontend by making it effortless to have a custom API."
  homepage ""
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fdemir/havlu/releases/download/v0.3.2/havlu_Darwin_arm64.tar.gz"
      sha256 "7f652bf7cbb5db75307cc690f4cd496322b2e56fbf5a1dd7ff073f6210ef554b"

      def install
        bin.install "havlu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fdemir/havlu/releases/download/v0.3.2/havlu_Darwin_x86_64.tar.gz"
      sha256 "3a2b1a936781a33458b38b510d05536e182840dc5dbaaa769229a28f969a3527"

      def install
        bin.install "havlu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fdemir/havlu/releases/download/v0.3.2/havlu_Linux_arm64.tar.gz"
      sha256 "eb06848eb2540022d83903e644d40f4b8d838144a8b898e7bb57f34bc3005e84"

      def install
        bin.install "havlu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fdemir/havlu/releases/download/v0.3.2/havlu_Linux_x86_64.tar.gz"
      sha256 "1191b916a08c996fa21aed8dd189be7f69e0a4fef78922cf8b639bd7595a3923"

      def install
        bin.install "havlu"
      end
    end
  end
end
