# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Havlu < Formula
  desc "Havlu lets you focus on the frontend by making it effortless to have a custom API."
  homepage ""
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fdemir/havlu/releases/download/v0.2.0/havlu_Darwin_arm64.tar.gz"
      sha256 "c9971d49a5e0c557e4b376b2757a8acc87c9deeaae812b75460f4dd0ff701e40"

      def install
        bin.install "havlu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fdemir/havlu/releases/download/v0.2.0/havlu_Darwin_x86_64.tar.gz"
      sha256 "9f1d2241f0f10c9f21cc83d5d4c8ac60f5de96403a1e1898487abe32986c7d3f"

      def install
        bin.install "havlu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fdemir/havlu/releases/download/v0.2.0/havlu_Linux_arm64.tar.gz"
      sha256 "89e80e0cae5e46a5cb86b5a240af1dde53e90d1583a8ad3ae650aa52545d7997"

      def install
        bin.install "havlu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fdemir/havlu/releases/download/v0.2.0/havlu_Linux_x86_64.tar.gz"
      sha256 "219c0f4f293a2ef687512d15549c2bae93d98ba2c76c84f2371fee64ed9e8db7"

      def install
        bin.install "havlu"
      end
    end
  end
end
